### Build a DNN using Keras with `RELU` and `ADAM`


### Load tensorflow

In [1]:
import tensorflow as tf
tf.reset_default_graph()
tf.set_random_seed(42)
import pandas as pd
import numpy as np
import keras
from keras.utils import np_utils

Using TensorFlow backend.


In [2]:
from keras.datasets import fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()


4423680/4422102 [==============================] - 1s 0us/step


In [3]:
# Displaying the shape of training dataset
x_train.shape
print(x_train.shape[0], 'train samples')

60000 train samples


In [4]:
#Displaying the shape of Test dataset
x_test.shape
print(x_test.shape[0], 'test samples')

10000 test samples


### Convert train and test labels to one hot vectors

In [5]:
# convert integers to dummy variables (i.e. one hot encoded)
dummy_ytrain = np_utils.to_categorical(y_train)
print(dummy_ytrain)
dummy_ytest = np_utils.to_categorical(y_test)
print(dummy_ytest)

[[0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


## Build the Graph
### Initialize model, reshape & normalize data

In [6]:
#Initializing a Sequential model
model = tf.keras.models.Sequential()

#Reshaping data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28,)))

#Normalizing the data
model.add(tf.keras.layers.BatchNormalization())

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
print('x_train shape:', x_train.shape)
print(x_train.shape[0], 'are the train samples')
print(x_test.shape[0], 'are the test samples')

x_train shape: (60000, 28, 28)
60000 are the train samples
10000 are the test samples


###Add two fully connected layers with 200 and 100 neurons respectively with relu activations. Add a dropout layer with p=0.25


In [8]:
#Adding 1st FC layer with relu activation
model.add(tf.keras.layers.Dense(200, activation='relu'))

#Adding 2nd FC layer with relu activation
model.add(tf.keras.layers.Dense(100, activation='relu'))

# Adding a dropout layer of 0.25
model.add(tf.keras.layers.Dropout(0.25))

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


### Add the output layer with a fully connected layer with 10 neurons with softmax activation. Use categorical_crossentropy loss and adam optimizer and train the network. And, report the final validation.


In [0]:
#Adding output layer with 10 neurons and softmax activation
model.add(tf.keras.layers.Dense(10, activation='softmax'))

# Loss and Optimizer and metrics
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [10]:
# Fitting  the model
model.fit(x_train, dummy_ytrain, batch_size=35, nb_epoch=10, 
        validation_data=(x_test, dummy_ytest))

Train on 60000 samples, validate on 10000 samples
Instructions for updating:
Use tf.cast instead.
Epoch 1/10
60000/60000 [==============================] - 11s 184us/sample - loss: 0.5077 - acc: 0.8180 - val_loss: 0.3990 - val_acc: 0.8528
Epoch 2/10
60000/60000 [==============================] - 10s 168us/sample - loss: 0.3891 - acc: 0.8581 - val_loss: 0.3739 - val_acc: 0.8634
Epoch 3/10
60000/60000 [==============================] - 10s 168us/sample - loss: 0.3566 - acc: 0.8691 - val_loss: 0.3466 - val_acc: 0.8735
Epoch 4/10
60000/60000 [==============================] - 10s 169us/sample - loss: 0.3278 - acc: 0.8793 - val_loss: 0.3526 - val_acc: 0.8752
Epoch 5/10
60000/60000 [==============================] - 10s 169us/sample - loss: 0.3106 - acc: 0.8847 - val_loss: 0.3540 - val_acc: 0.8782
Epoch 6/10
60000/60000 [==============================] - 10s 167us/sample - loss: 0.2933 - acc: 0.8905 - val_loss: 0.3731 - val_acc: 0.8782
Epoch 7/10
60000/60000 [==============================] 

In [11]:
# Finding the Training accuracy
score = model.evaluate(x_train, dummy_ytrain)
print('Training accuracy: ', score[1])

60000/60000 [==============================] - 4s 63us/sample - loss: 0.1995 - acc: 0.9255
Training accuracy:  0.92546666


In [12]:
# Finding the Test accuracy
score = model.evaluate(x_test, dummy_ytest)
print('Training accuracy: ', score[1])

10000/10000 [==============================] - 1s 64us/sample - loss: 0.3420 - acc: 0.8880
Training accuracy:  0.888


#Word Embeddings in Python with Gensim
In this, you will practice how to train and load word embedding models for natural language processing applications in Python using Gensim.

How to train your own word2vec word embedding model on text data.
How to visualize a trained word embedding model using Principal Component Analysis.
How to load pre-trained word2vec word embedding models.
##Run the below two commands to install gensim and the wiki dataset

In [13]:
!pip install --upgrade gensim --user

    100% |████████████████████████████████| 24.2MB 2.0MB/s 


In [14]:
!pip3 install wikipedia --user

  Stored in directory: /root/.cache/pip/wheels/87/2a/18/4e471fd96d12114d16fe4a446d00c3b38fb9efcb744bd31f4a
Successfully built wikipedia


In [0]:
# importing gensim
import gensim

## Obtain Text
Import search and page functions from wikipedia module search(/key word/): search function takes keyword as argument and gives top 10 article titles matching the given keyword.

page(/title of article/): page function takes page title as argument and gives content in the output.

In [16]:
# Import wikipedia library
#!pip install wikipedia
import wikipedia
from wikipedia import search, page

# search function for machine learning keyword
titles = search("Machine Learning")

ModuleNotFoundError: ignored

In [0]:
# ! pip install -r requirements.txt
# ! bash runtests  # will run tests for python and python3
# ! python -m unittest discover tests/ '*test.py'  # manual style